### ISSUE TITLE
Permission/Ownership Problem caused by The Script 

### ISSUE THREAD

**Issue by thejackal2017** [DRM-Scripts/SlingX#3]
Hi, I noticed the following line in the installation Script (install.sh):

`chown -R mini_cs:mini_cs /home`

I think this will give the user mini_cs the ownership of all Directories/Files under /home directory , if another panel is installed previously in the /home dir , this may cause a problem for it to run as it happened in the xui.one panel and i had to change the ownership back to user xui again to be able to login to the panel again. 

it is a better idea to change the ownership only for the directories related to the script . 

One last thing ,I know that "NO SUPPORT Will BE PROVIDED" ,but  i installed the script without any problem and tried to activate a number of channels ,but still no luck and the links generated by it not working , so is this script really working ? or had some issues with it like it requires  a proxy for it to work ? 

Regards

**Comment by iptvtest123** [comment]
I can't find the place to deposit the Sling account

**Comment by DRM-Scripts** [comment]
> Hi, I noticed the following line in the installation Script (install.sh):
> 
> `chown -R mini_cs:mini_cs /home`
> 
> I think this will give the user mini_cs the ownership of all Directories/Files under /home directory , if another panel is installed previously in the /home dir , this may cause a problem for it to run as it happened in the xui.one panel and i had to change the ownership back to user xui again to be able to login to the panel again.
> 
> it is a better idea to change the ownership only for the directories related to the script .
> 
> One last thing ,I know that "NO SUPPORT Will BE PROVIDED" ,but i installed the script without any problem and tried to activate a number of channels ,but still no luck and the links generated by it not working , so is this script really working ? or had some issues with it like it requires a proxy for it to work ?
> 
> Regards

I’d advise running this on its own and not with any other script installed on the server.
